apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: SampleDefaultTransformer
  labels:
    move2kube.konveyor.io/built-in: false
spec:
  class: "Starlark"
  directoryDetect:
    levels: 0
  config:
    starFile: "defaulttransformer.star"
  invokedByDefault:
    enabled: true
